In [4]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
print(np.sum(arr))
print(arr.sum())
print(np.mean(arr))
print(np.median(arr))
print(np.min(arr))
print(np.max(arr))
print(np.std(arr))
print(np.var(arr))
print(np.argmin(arr))
print(np.argmax(arr))

150
150
30.0
30.0
10
50
14.142135623730951
200.0
0
4


In [9]:
# Aggregation on 2d
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print(np.sum(arr))
print(np.sum(arr,axis=0))
print(np.sum(arr,axis=1))

21
[5 7 9]
[ 6 15]


In [15]:
# Boolean Indexing (Filtering)
scores = np.array([45, 78, 92, 33, 88, 65, 71])

mask = scores > 70
print(mask)
print(scores[mask])

print(scores[scores > 70])

mask2=(scores>70) & (scores<90)
mask2=(scores<35) | (scores>90)
print(scores[mask2])

[False  True  True False  True False  True]
[78 92 88 71]
[78 92 88 71]
[92 33]


In [17]:
# Fancy Indexing
arr = np.array([10, 20, 30, 40, 50, 60, 70])
print(arr[[0, 3, 5]])
print(arr[[6, 2, 0]])


[10 40 60]
[70 30 10]
