In [11]:
import numpy as np

# List vs Numpy
my_list=[1,2,3,4,5]
result=[num*2 for num in my_list]
print(result)

arr=np.array([1,2,3,4,5])
result=arr*2
print(result)

[2, 4, 6, 8, 10]
[ 2  4  6  8 10]


In [15]:
# Create Arrays: From python data
arr1=np.array([1,2,3,4,5])
print(arr1)

arr2=np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
print(arr2)

arr3=np.array([1,2,3,4,5],dtype=np.float64)
print(arr3)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1. 2. 3. 4. 5.]
