In [4]:
# How to create arrays using inbuilt functions

import numpy as np

zeros=np.zeros((3,6))
print(zeros)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [7]:
ones=np.ones((4,5))
print(ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [10]:
arr=np.full((3,3),100)
print(arr)

[[100 100 100]
 [100 100 100]
 [100 100 100]]


In [13]:
identity=np.eye(5)
print(identity)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
# Creating array: Ranges & Random
arr=np.arange(0,13,3)
print(arr)

[ 0  3  6  9 12]


In [20]:
arr=np.linspace(1,50,8)
print(arr)

[ 1.  8. 15. 22. 29. 36. 43. 50.]


In [23]:
arr=np.random.randint(1,100,size=(3,3))
print(arr)

[[90 94 33]
 [24 69 81]
 [59 67 84]]


In [24]:
arr=np.random.random((3,3))
print(arr)

[[0.66065354 0.76545736 0.76163366]
 [0.98592545 0.64941548 0.19257346]
 [0.04282779 0.11497201 0.26698173]]
