In [7]:
import numpy as np

a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])

print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a ** 2)

# Masking
print(a > 20)

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]
[ 100  400  900 1600]
[False False  True  True]


Broadcasting

In [ ]:
# Scalar Broadcast
arr = np.array([1, 2, 3, 4])
print(arr * 10)
print(arr + 10)

[10 20 30 40]
[101 102 103 104]


In [13]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
row = np.array([10, 20, 30])

print(matrix * row)

[[ 10  40  90]
 [ 40 100 180]]
