In [9]:
import numpy as np


arr = np.array([10, 20, 30, 40, 50])
# Single element
print(arr[0])
print(arr[-1])

# Slicing
print(arr[1:4])
print(arr[:3])
print(arr[::2])
print(arr[::-2])

10
50
[20 30 40]
[10 20 30]
[10 30 50]
[50 30 10]


In [15]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print(arr[0, 2])
print(arr[2, 1])

# Entire row / column
print(arr[1])
print(arr[:, 0])
print(arr[0:2, 1:3])


3
8
[4 5 6]
[1 4 7]
[[2 3]
 [5 6]]
