In [3]:
# Stacking Arrays
import numpy as np


a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.vstack([a, b]))
print(np.hstack([a, b]))

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [5]:
# 2d arrays
m1 = np.array([[1, 2], 
               [3, 4]])

m2 = np.array([[5, 6], 
               [7, 8]])

print(np.vstack([m1, m2]))
print(np.hstack([m1, m2]))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
